language: c

install:
 - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install
        expect
        gir1.2-gstreamer-1.0
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        gstreamer1.0-plugins-good
        gstreamer1.0-tools
        gstreamer1.0-x
        moreutils
        pep8
        python-docutils
        python-flask
        python-gobject
        python-jinja2
        python-nose
        python-numpy
        python-opencv
        python-yaml
        tesseract-ocr
        tesseract-ocr-deu
        tesseract-ocr-eng
        xdotool
        xserver-xorg-video-dummy
        xterm
 - sudo pip install isort pylint==1.1.0
 - git clone http://git.chromium.org/webm/webminspector.git ~/webminspector
 - wget http://ftpmirror.gnu.org/parallel/parallel-20140522.tar.bz2 &&
   tar -xvf parallel-20140522.tar.bz2 &&
   cd parallel-20140522/ &&
   ./configure --prefix=/usr/local &&
   make &&
   sudo make install &&
   cd .. &&
   rm -Rf parallel-20140522/ &&
   mkdir $HOME/.parallel &&
   touch $HOME/.parallel/will-cite  # Silence citation warning
 - make

script:
 - PATH=~/webminspector:$PATH make check
