language: c

install:
 - sudo apt-get update
 - sudo apt-get install gstreamer0.10-plugins-base
                        python-gst0.10 python-docutils
                        python-nose xvfb
                        gstreamer0.10-tools gstreamer0.10-x
                        gstreamer0.10-plugins-good pylint pep8
                        python-numpy python-opencv
 - make

script:
 - xvfb-run -s "-screen 0 1024x768x24" make check
